### PR TITLE
Add Window#background_color

### PR DESCRIPTION
**Pull request by Kjarrigan**
While I looked through the code to remember how the rendering stuff works to figure out if [this](https://wiki.delphigl.com/index.php/Screenshot) would work as an easy screenshot command #317 I remembered an old wish of mine to change the window background color. And there right in the code was already a _clear_with_color_ variable - at least until I pulled the latest master. So this PR reverts some of the latest changes and provide a function to actually manipulate the _clear_with_color_-value.

I guess the rest is self-explaining.

### CODE REVIEW

**Comment by jlnr** [comment]
I like the implementation (although RED is not a good default :P) but I don't think the feature is worth the extra callback. If the user wants a different background colour, they can fix it with a single `draw_rect` call. That's also why I've removed the argument to `frame`. Sorry, I'm going to defend Gosu's small interface here again :)

**Comment by Kjarrigan** [comment]
Yeah the red was for testing if it works and somehow survived the cleanup :smile: No problem. I have some more ideas so plenty of chances to get something merged :grin:

**Comment by akicho8** [comment]
I recently started using Gosu. However, I am having trouble figuring out how to change the background color, which is why I ended up here. I know that you can overwrite it by calling draw_rect, but isn't that a waste of processing if I could specify the color from the beginning?

**Comment by jlnr** [comment]
Using `draw_rect` should not have a measurable impact on rendering. You can render tens of thousands of rectangles per frame even using old hardware. Also, I suspect that most game projects that are approaching completion will use background textures anyway, not solid colors.

**Comment by akicho8** [comment]
Thank you for your prompt response!
I wasn't aware that draw_rect was that fast, even for filling the entire screen. I understand that the background would typically be texturized in most modern games, but my purpose for using Gosu is to simulate physical movements. Therefore, simply clearing the screen with a single color in the fastest way possible is more than enough for my needs. For now, I'm going to proceed with the method of using draw_rect.

**Pull request closed without merging**
