### PR TITLE
Add first unit tests to Gosu (#360)

### PR DESCRIPTION
**Pull request by jlnr**

### CODE REVIEW

**Comment by jlnr** [comment]
@Kjarrigan I've stolen some tests from #360 and added the interface comparison I was thinking about. Still trying to get my tests to run on the Linux CI, then I'll push fixes for the red tests and merge this - and you can rebase the other tests that you have on it (calling `draw_line` etc. outside of `Window#draw`)

**Comment by jlnr** [comment]
AAHHH WTF MICROSOFT. I've wasted quite some time getting the tests to work on Windows, when they worked all along. It's just that any program that prints *anything* to `stderr` triggers an error in PowerShell, even when the exit code is 0. Windows, not even once.

**Comment by Kjarrigan** [comment]
> Windows, not even once.
FullAck :smile: 
I'm glad that you figured that out, so the path as clear for the first gosu unit test :+1: ?!

**Comment by jlnr** [comment]
For future reference, a bit of discussion happened in this commit, which has later been rebased: https://github.com/gosu/gosu/commit/0ec4a732e59acc4d8f8b52db3f5242a547f15dd8#commitcomment-20396274

**Comment by Kjarrigan** [comment]
```
  KB_0…KB_9 = :an_integer
  KB_A…KB_Z = :an_integer
```

I like that new format a lot. Its definitely much cleaner than before. I still hope to get some groups in the future :smile: as I usually really just want to know the name of the button const and not the "flavour" text.
[PR yard#1056](https://github.com/lsegal/yard/pull/1056)

**Pull request merged**
