### PR TITLE
Make README.txt README.md and update formatting

### PR DESCRIPTION
**Pull request by mhsjlw**
I have renamed README.txt to README.md and update formatting to include links

### CODE REVIEW

**Comment by jlnr** [comment]
Thanks! I've looked at the README.md in your account, and I think I'd also turn the irc:// URL into a link. And I think the packaging files need to be updated, as I think they all contain the README.md.
I can quickly go over these myself, but probably not this week :(

**Comment by mhsjlw** [comment]
@jlnr I have tried to make the irc link clickable but, GitHub (from what I know) doesn't allow non http links to be used as hyper links. I could however use the web version of freenode if you'd like.

**Comment by jlnr** [comment]
Oh, thanks, I wasn't aware of this limitation. You are right, irc:// links don't seem to work, not even as direct HTML <a> tags. Web client link sounds good!
Also, all URLs in the README should use https:// instead of http:// (both github.com and libgosu.org), and I think the email link has two extra slashes.
Again, thanks for looking into this long-overdue conversion :)

**Comment by mhsjlw** [comment]
@jlnr No problem, I'll update the PR now

**Comment by mhsjlw** [comment]
Also, yes I made a mistake with the `mailto` link. It is `mailto:` not `mailto://`

**Comment by mhsjlw** [comment]
Done.

**Comment by jlnr** [comment]
Thanks, merged. I'll go ahead with additional edits...parts of the README have actually been outdated :)

**Pull request merged**
