### PR TITLE
Support Xenial

### PR DESCRIPTION
**Pull request by pusewicz**
Closes https://github.com/gosu/gosu/issues/478

### CODE REVIEW

**Comment by pusewicz** [comment]
@jlnr I've opened this as a Draft first to see if it builds fine in Travis, but I can see no job being kicked-off? Do I need to do anything special to trigger it?

**Comment by jlnr** [comment]
Regarding the actual PR contents, I think the goal should be to replace the old Trusty base by Xenial, not to supplant it. That way we can start to use newer C++ language constructs.

Not sure why it's not building! As a general heads-up, I would advise you (and also @cyberarm who did another CI-related PR) to keep an eye on how whether Travis still operates as expected, context: https://news.ycombinator.com/item?id=19218036

**Comment by pusewicz** [comment]
@jlnr Yeah, absolutely, I first wanted to add Xenial, to see if it builds at all. I'll see if changing the config file again triggers it.

**Comment by cyberarm** [comment]
@pusewicz Might be able to use pulseaudio's dummy sound output.

https://github.com/travis-ci/travis-ci/issues/9149#issue-291913854
http://manpages.ubuntu.com/manpages/xenial/en/man1/pulseaudio.1.html

**Comment by pusewicz** [comment]
@cyberarm That seems to have made the trick!

**Comment by jlnr** [comment]
Thanks a lot everyone! 🎉🎉🎉 Merging now. @Kjarrigan Feel free to resurrect this ticket if you think going for pulseaudio is the wrong direction here :)

**Pull request merged**
