### PR TITLE
Replace OpenAL with mojoAL

### PR DESCRIPTION
**Pull request by cyberarm**

### CODE REVIEW

**Comment by cyberarm** [comment]
@jlnr Do you want podspec updated to use mojoAL or leave that be for now?

**Comment by jlnr** [comment]
Yes please, let's replace it all :)

**Comment by cyberarm** [comment]
@jlnr I got all the CI passing. iOS and OSX should probably get manually checked to ensure they work as expected.
I tested sound on Windows and Linux, however I am unable to test iOS and OSX.

**Comment by cyberarm** [comment]
iOS still uses OpenAL since mojoAL relies on SDL and Gosu's iOS implementation doesn't use SDL as far as I know.

**Review by jlnr — APPROVED** [review]
Had to add the header_mappings_dir so that installation through CocoaPods also works on macOS. Otherwise it seems to work just fine. Thanks so much!! Can't wait to never see oal-soft warnings in my Linux  terminals :)

**Pull request merged**
