### PR TITLE
Quake2 allocblock

### PR DESCRIPTION
**Pull request by pmer**
Hello,

I am just presenting this here so that a final statement can be made on whether to include this or not.

This branch implements Quake 2's block allocator, which improves Gosu's speed with allocating images.

Cheers,
Jamer

### CODE REVIEW

**Comment by jlnr** [comment]
FWIW here's a public domain library for rect allocation here: https://github.com/nothings/stb/blob/master/stb_rect_pack.h

**Comment by pmer** [comment]
And here's a page that lists a set of algorithms that solve this problem: http://cgi.csc.liv.ac.uk/~epa/surveyhtml.html#toc.2

**Comment by pmer** [comment]
Okay, here's a proposal:

Let W and H be the width and height of whole tiled image in pixels, and let X and Y be the width of an individual tile.

Currently we treat each of the X * Y tiles as an object that needs to be packed. What if, in an effort to reduce the work done, we try to put all the tiles next to each other? That is, since we want a 1-pixel margin around each tile, what if we look for a free space that is (W + X - 1) * (H + Y - 1). Then we place the tiles within this space, since there will be enough room.

This will not pack objects as densely as we do now.

We can take advantage of the fact that these images are related (they're more likely than a normal set of images to either all be used or all not be used) to achieve a second optimization. We can treat the set of X * Y images as a single block in the texture memory when searching for unallocated places in memory when uploading further images, which reduces the computational complexity of future allocations.

In order provide this second optimization, we wouldn't free any tile from texture memory until all related tiles from a single tiled image have been freed.

One negative consequence of this second optimization is that if someone calls `loadTiles()` but only wants to keep a few of the images produced, and they free the rest, we'll continue using more memory than necessary.

**Comment by pmer** [comment]
Not sure if this is useful, but here's an allocater from webrender.

https://github.com/servo/webrender/blob/122ba09/webrender/src/texture_cache.rs#L75-L82

In [the webrender introduction video](https://air.mozilla.org/bay-area-rust-meetup-february-2016/), @pcwalton says it's fast. Not sure this algorithm fits the needs of Gosu games. Should be looked into.

**Comment by jlnr** [comment]
Ah, nice! I like that the comment specifically mentions *deallocation*.

**Comment by pmer** [comment]
I've started working on this, but I'm going pretty slowly. 🙂

**Comment by jlnr** [comment]
Wow, 9 years. Sorry that I've never really reviewed this in depth, but thanks for also opening #534 :+1:

**Comment by jlnr** [comment]
12 years now... and I finally implemented something like this in #658. Thanks again for opening both tickets, the comment in the Rust source code led me in the right direction.

**Comment by pmer** [comment]
Ah, that's wonderful! If we lived in the same town, I'd say let's go out and celebrate. Nicely done! :)

Appreciate the quality of comments in that PR, too.

**Comment by jlnr** [comment]
Thanks :) This was always one of the topics that I really wanted to get back to, but it was certainly a lot more fun to work on this now with proper C++ unit tests and tooling.

**Pull request closed without merging**
